export * from './components/forms/address-info/address-info.component';
export * from './components/forms/tutor-info/tutor-info.component';
export * from './components/forms/user-general-info/user-general-info.component';
export * from './components/user-details-form/user-details-form.component';
export * from './directives/form-component.directive';
export * from './form-controls/address-info.form';
export * from './form-controls/tutor-info.form';
export * from './form-controls/user-general-info.form';
export * from './models/user-details-form-model';
